### ISSUE TITLE
No edge in adjacency matrix! Nothing to show here.

### ISSUE THREAD

**Issue by PoisonAlien** [BIMIB-DISCo/TRONCO#43]
I'm using TRONCO for progression model on one of our project involving hematological cancer. We have very low mutational load to begin with. Everything seems to work , but during `tronco.plot(model)`, I get 

```
NULL
Warning message:
In tronco.plot(apl.model) :
  No edge in adjacency matrix! Nothing to show here.
```

Is this because of low mutation numbers ? Any parameters I need to tune in ?

**Comment by caravagn** [comment]
Hi, it could be that if mutations have very low frequencies the model inferred is empty (so you have no edges). Could you please tell which algorithm/parameters did you use or could you post the output of a call to oncoprint?

What does the call to 

> as.selective.advantage.relations(m)

where 'm' is your model returns?

**Comment by PoisonAlien** [comment]
Hi, yes, the inferred model has no edges. I ran CAPRI with default parameters. 
I have sample size of 125 with 257 mutations, two mutual exclusive events, and no copy number data. 
I have attached an oncorprint for your reference. 

running `as.selective.advantage.relations(m)` returns NULL values for aic and bic.

![oncoprint](https://cloud.githubusercontent.com/assets/8164062/10557597/f700d730-74e5-11e5-9f9d-12c0763031c4.png)

**Comment by danro9685** [comment]
Dear PoisonAlien,

as pointed out, the reason for the error message you obtain is the fact that the algorithm cannot infer any progression model given the input data. There can be different reasons for this result.

Indeed, looking at the oncoprint profiles you provide, it seems that the overlap among the different alterations you consider is minimal. And it seems reasonable not to find any statistically significant relation of selective advantage.

I'm not sure which type of cancer you are studying, but we found that, in general, some blood cancers such as leukemia, because of their intrinsic aggressivity, present very low mutation rate leading to think to a much faster progression (i.e., through a lower number of alterations), hence making the inference harder.

However, you may want to further analyze this by for instance going back to the selection of the relevant alterations (I see only 7 alterations in the oncoprint) and by looking for any relevant subtype in your tumors (the sample size is more than enough being 125 cases).

Please don't hesitate to write if you need further help.

Best,
Daniele

**Comment by PoisonAlien** [comment]
Hi Daniele,

Thanks so much honest reply. I do suspect the same. Yes, we are studying a specific subtype of leukemia and mutation load is very low, in fact majority of the sample have as low as single mutation, making it harder to find overlapping alterations. Anyways thanks again for the advice and a great package.

**Comment by danro9685** [comment]
You are very welcome! 

Daniele
